### ISSUE TITLE
CSR形式のStatic Graphライブラリ

### ISSUE THREAD

**Issue by seekworser** [kemuniku/cplib#170]
https://qiita.com/AkariLuminous/items/31faea745b5dd4fb9edc

**Comment by kemuniku** [comment]
かなりほしい

**Comment by kemuniku** [comment]
これやらないとほかのグラフ系に手を出せない気がしている

**Comment by seekworser** [comment]
かなり偉い
CSR (842ms)
https://atcoder.jp/contests/abc324/submissions/50254677
Adj (1900ms)
https://atcoder.jp/contests/abc324/submissions/50254686

**Comment by kemuniku** [comment]
私の通常実装のほうが速い(400ms)
https://atcoder.jp/contests/abc324/submissions/50254938

**Comment by seekworser** [comment]
ちょっとだけ偉い
![image](https://github.com/kemuniku/cplib/assets/33556634/3fe3fa2a-37f1-4022-b7db-8ace29175508)
