### ISSUE TITLE
双方向連結リスト

### ISSUE THREAD

**Issue by kemuniku** [kemuniku/cplib#177]
https://atcoder.jp/contests/abc344/tasks/abc344_e
が吐くほど苦しかったので

**Comment by kemuniku** [comment]
https://nim-lang.org/docs/lists.html
で十分かもしれない

**Comment by seekworser** [comment]
`std/lists` が結構使いやすかったので一応提出リンク、かなり直感的に使える
https://atcoder.jp/contests/abc350/submissions/52626052
`add`、`prepend`の引数には他のListも取れるが、O(1)でくっつけるには`addMoved`、`prependMovec`を使用する必要があるのに注意

**Comment by kemuniku** [comment]
ここら辺があると、さらに便利そう
https://scrapbox.io/atcodernim/Nim%E3%81%AElists%E3%81%A7ABC344_E_-_Insert_or_Erase%E3%82%92%E9%80%9A%E3%81%97%E3%81%9F%E3%81%84

**Comment by kemuniku** [comment]
上記の記事の関数を追加したいです

**Comment by seekworser** [comment]
head, tail周りに関しては、ダミーで一個ずつ入れることにしておくと条件分岐が減って楽、という話もあったり

**Comment by kemuniku** [comment]
うーん、普通にやるならそうやって実装するけどライブラリだとちゃんと場合分けしたいなぁ。

**Comment by seekworser** [comment]
なるほどなぁ、たしかに

**Comment by kemuniku** [comment]
https://atcoder.jp/contests/arc050/tasks/arc050_d

**Comment by kemuniku** [comment]
#476
