### ISSUE TITLE
Functional Graphテンプレ

### ISSUE THREAD

**Issue by kemuniku** [kemuniku/cplib#251]
いろいろできるとちょっと便利かもしれない
今のところやりたいこと
・サイクルへの距離(サイクルに含まれる場合は0)
・連結成分に存在するサイクルのサイクル長
・サイクルを取得
・x回辺の先へ移動を繰り返した後の頂点(x<=10^18)

**Comment by seekworser** [comment]
とりあえず前計算O(N)でlen_to_cycleとcycle_lenあたりを計算したい

**Comment by kemuniku** [comment]
前計算O(NlogN)かO(Nlog(10^18))かけてi個先の頂点をダブリングするやつが欲しい説もある

**Comment by kemuniku** [comment]
あとはサイクルに属しているかのboolとか？

**Comment by kemuniku** [comment]
あとはget cycleとか(O(N)でいいので)

**Comment by kemuniku** [comment]
サイクルに属しているかのboolは、サイクルまでの距離(属しているならば0)の配列の作成で対応しましょう

**Comment by kemuniku** [comment]
i頂点先ってO(N)/O(1)でできるっけ

**Comment by seekworser** [comment]
できる気がしてきた

- グラフをパスとサイクルに分離して、それぞれにIDを振る
- それぞれ頂点の並びと、パスはどのサイクルの何番目に結合するか、を持つ
- 各頂点ごとに属するパス or サイクルのIDとその中で何番目の頂点か、を持っておく

**Comment by kemuniku** [comment]
パスではなく木なのでむりじゃないかなぁになった
Level Ancestor Problem がクエリO(logN)なので

**Comment by seekworser** [comment]
ごめんなさいになった

**Comment by kemuniku** [comment]
<O(n), O(1)> LAが存在するらしいです(何？)

**Comment by kemuniku** [comment]
実用上は遅いらしいのでどうしようねといった感じ
1.全部ダブリングでやる log(10^18)とかまでもつ
2.一部ダブリングでやる log(木の深さ)
3.HL分解する メモリがO(N)になります

**Comment by seekworser** [comment]
備忘
https://37zigen.com/level-ancestor-problem/

**Comment by kemuniku** [comment]
そういえばLevel Ancestor Problem って今ない？(HL分解にありましたっけ)

**Comment by seekworser** [comment]
LAはあったはず

**Comment by seekworser** [comment]
個人的には実装軽いし1でいいいかなの気持ちがあります

**Comment by kemuniku** [comment]
2もそんなには重くないと思うぜ！

**Comment by seekworser** [comment]
ﾋｨﾝ………

**Comment by kemuniku** [comment]
頂点AからBに行くことはできるか、できるなら何回の移動で行くことができるか とか

**Comment by kemuniku** [comment]
https://x.com/maspy_stars/status/1559842309688008707?s=61

**Comment by kemuniku** [comment]
https://atcoder.jp/contests/abc367/editorial/10719

**Comment by kemuniku** [comment]
https://atcoder.jp/contests/abc367/submissions/58138396
