### ISSUE TITLE
{.global.} pragmaを用いているコードをarcで動作させないようにする

### ISSUE THREAD

**Issue by kemuniku** [kemuniku/cplib#308]
ただし、{.global.} pragmaを用いても正常動作するような型もあるようなので要検証。

確実に壊れているもの

- AVL木

{.global.}が使われているもの

- [barrett_impl.nim](https://github.com/kemuniku/cplib/blob/d6ecad04f34d921b2bf7131e9f194ede89be5d97/src/cplib/modint/barrett_impl.nim#L13)
- [montgomery_impl.nim](https://github.com/kemuniku/cplib/blob/d6ecad04f34d921b2bf7131e9f194ede89be5d97/src/cplib/modint/montgomery_impl.nim#L20)

**Comment by kemuniku** [comment]
対応方法
https://github.com/kemuniku/cplib/issues/304#issuecomment-2227275107

**Comment by seekworser** [comment]
yukicoder で CE になることを確認
https://yukicoder.me/submissions/996907

**Comment by seekworser** [comment]
AtCoder はエラーなし、大丈夫そう
https://atcoder.jp/contests/arc033/submissions/55856545
