### ISSUE TITLE
rootに値を持つUnionFind

### ISSUE THREAD

**Issue by kemuniku** [kemuniku/cplib#337]
uniteするときに、rootの2つの値x,yからf(x,y)を求め、新たなrootに保存する。

**Comment by seekworser** [comment]
ちょっと毛色は違うかもだけど、こういうインターフェースもある
https://nachiavivias.github.io/cp-library/cpp/set/dsu.html

```nim
uf.unite(x, y, f(uf[x], uf[y]))
```
