### ISSUE TITLE
高速なHashset、Hashmap

### ISSUE THREAD

**Issue by seekworser** [kemuniku/cplib#49]
作る

**Comment by seekworser** [comment]
https://en.wikipedia.org/wiki/Open_addressing
https://x.com/noshi91/status/1643524879680159745?s=20

**Comment by seekworser** [comment]
https://postd.cc/designing-a-fast-hash-table/

**Comment by kemuniku** [comment]
Associative Array
https://judge.yosupo.jp/problem/associative_array

**Comment by seekworser** [comment]
これはダメかもしれない
https://atcoder.jp/contests/abc340/submissions/50190691

**Comment by kemuniku** [comment]
急に重要度が高くなった
