### ISSUE TITLE
HL分解

### ISSUE THREAD

**Issue by kemuniku** [kemuniku/cplib#63]
[Vertex Add Path Sum](https://judge.yosupo.jp/problem/vertex_add_path_sum)
[Vertex Set Path Composite](https://judge.yosupo.jp/problem/vertex_set_path_composite)
[Vertex Add Subtree Sum](https://judge.yosupo.jp/problem/vertex_add_subtree_sum)

**Comment by kemuniku** [comment]
https://nachiavivias.github.io/cp-library/cpp/tree/heavy-light-decomposition.html

**Comment by kemuniku** [comment]
NimのHL分解が生えたらしいです(?)
https://gist.github.com/NachiaVivias/2468bb1f9b7fbccd0af4e2114a139f97

**Comment by seekworser** [comment]
@kemuniku これやってもいいですか（HLDを早めに入れちゃいたいので）
